
name: lint the code

on: workflow_dispatch

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name : get the code
              uses: actions/checkout@v4
            - name : check node version
              run: 'node -v'